library(shiny)
library(shinydashboard)
library(fresh)
library(DT)
library(randomForest)
library(ggplot2)
library(ggfortify)
library(MASS)
library(dplyr)
library(corrplot)
library(reshape2)
library(rpart)
library(rpart.plot)
library(party)
library(ggraph)
library(igraph)
library(pdp)
library(caret)
library(e1071)
library(data.table)
library(hash)
library(openssl)

source("ui.R")
source("server.R")

# Shiny App ---------------------------------------------------------------

shinyApp(ui, server)